version: 2
updates:
- package-ecosystem: cargo
  directory: "/src/program-rust"
  schedule:
    interval: daily
    time: "01:00"
    timezone: America/Los_Angeles
  labels:
   - "automerge"
  open-pull-requests-limit: 3
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
    timezone: America/Los_Angeles
  labels:
    - "automerge"
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - "> 6.15.0"
  - dependency-name: eslint
    versions:
    - 7.25.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@types/eslint"
    versions:
    - 7.2.6
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
  - dependency-name: "@types/prettier"
    versions:
    - 2.1.6
    - 2.2.0
